<div class="card">
    <div class="card-body">
      <h4 class="page-header m-t">Action</h4>
      <div class="row list-icon">
        <div class="col-xs-6 col-md-4"><i class="mdi-action-3d-rotation i-24 m-t-sm"></i><span>mdi-action-3d-rotation</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-accessibility i-24 m-t-sm"></i><span>mdi-action-accessibility</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-account-balance i-24 m-t-sm"></i><span>mdi-action-account-balance</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-account-balance-wallet i-24 m-t-sm"></i><span>mdi-action-account-balance-wallet</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-account-box i-24 m-t-sm"></i><span>mdi-action-account-box</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-account-child i-24 m-t-sm"></i><span>mdi-action-account-child</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-account-circle i-24 m-t-sm"></i><span>mdi-action-account-circle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-add-shopping-cart i-24 m-t-sm"></i><span>mdi-action-add-shopping-cart</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-alarm i-24 m-t-sm"></i><span>mdi-action-alarm</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-alarm-add i-24 m-t-sm"></i><span>mdi-action-alarm-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-alarm-off i-24 m-t-sm"></i><span>mdi-action-alarm-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-alarm-on i-24 m-t-sm"></i><span>mdi-action-alarm-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-android i-24 m-t-sm"></i><span>mdi-action-android</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-announcement i-24 m-t-sm"></i><span>mdi-action-announcement</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-aspect-ratio i-24 m-t-sm"></i><span>mdi-action-aspect-ratio</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assessment i-24 m-t-sm"></i><span>mdi-action-assessment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assignment i-24 m-t-sm"></i><span>mdi-action-assignment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assignment-ind i-24 m-t-sm"></i><span>mdi-action-assignment-ind</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assignment-late i-24 m-t-sm"></i><span>mdi-action-assignment-late</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assignment-return i-24 m-t-sm"></i><span>mdi-action-assignment-return</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assignment-returned i-24 m-t-sm"></i><span>mdi-action-assignment-returned</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-assignment-turned-in i-24 m-t-sm"></i><span>mdi-action-assignment-turned-in</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-autorenew i-24 m-t-sm"></i><span>mdi-action-autorenew</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-backup i-24 m-t-sm"></i><span>mdi-action-backup</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-book i-24 m-t-sm"></i><span>mdi-action-book</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-bookmark i-24 m-t-sm"></i><span>mdi-action-bookmark</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-bookmark-outline i-24 m-t-sm"></i><span>mdi-action-bookmark-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-bug-report i-24 m-t-sm"></i><span>mdi-action-bug-report</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-cached i-24 m-t-sm"></i><span>mdi-action-cached</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-class i-24 m-t-sm"></i><span>mdi-action-class</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-credit-card i-24 m-t-sm"></i><span>mdi-action-credit-card</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-dashboard i-24 m-t-sm"></i><span>mdi-action-dashboard</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-delete i-24 m-t-sm"></i><span>mdi-action-delete</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-description i-24 m-t-sm"></i><span>mdi-action-description</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-dns i-24 m-t-sm"></i><span>mdi-action-dns</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-done i-24 m-t-sm"></i><span>mdi-action-done</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-done-all i-24 m-t-sm"></i><span>mdi-action-done-all</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-event i-24 m-t-sm"></i><span>mdi-action-event</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-exit-to-app i-24 m-t-sm"></i><span>mdi-action-exit-to-app</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-explore i-24 m-t-sm"></i><span>mdi-action-explore</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-extension i-24 m-t-sm"></i><span>mdi-action-extension</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-face-unlock i-24 m-t-sm"></i><span>mdi-action-face-unlock</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-favorite i-24 m-t-sm"></i><span>mdi-action-favorite</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-favorite-outline i-24 m-t-sm"></i><span>mdi-action-favorite-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-find-in-page i-24 m-t-sm"></i><span>mdi-action-find-in-page</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-find-replace i-24 m-t-sm"></i><span>mdi-action-find-replace</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-flip-to-back i-24 m-t-sm"></i><span>mdi-action-flip-to-back</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-flip-to-front i-24 m-t-sm"></i><span>mdi-action-flip-to-front</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-get-app i-24 m-t-sm"></i><span>mdi-action-get-app</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-grade i-24 m-t-sm"></i><span>mdi-action-grade</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-group-work i-24 m-t-sm"></i><span>mdi-action-group-work</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-help i-24 m-t-sm"></i><span>mdi-action-help</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-highlight-remove i-24 m-t-sm"></i><span>mdi-action-highlight-remove</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-history i-24 m-t-sm"></i><span>mdi-action-history</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-home i-24 m-t-sm"></i><span>mdi-action-home</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-https i-24 m-t-sm"></i><span>mdi-action-https</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-info i-24 m-t-sm"></i><span>mdi-action-info</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-info-outline i-24 m-t-sm"></i><span>mdi-action-info-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-input i-24 m-t-sm"></i><span>mdi-action-input</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-invert-colors i-24 m-t-sm"></i><span>mdi-action-invert-colors</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-label i-24 m-t-sm"></i><span>mdi-action-label</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-label-outline i-24 m-t-sm"></i><span>mdi-action-label-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-language i-24 m-t-sm"></i><span>mdi-action-language</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-launch i-24 m-t-sm"></i><span>mdi-action-launch</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-list i-24 m-t-sm"></i><span>mdi-action-list</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-lock i-24 m-t-sm"></i><span>mdi-action-lock</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-lock-open i-24 m-t-sm"></i><span>mdi-action-lock-open</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-lock-outline i-24 m-t-sm"></i><span>mdi-action-lock-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-loyalty i-24 m-t-sm"></i><span>mdi-action-loyalty</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-markunread-mailbox i-24 m-t-sm"></i><span>mdi-action-markunread-mailbox</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-note-add i-24 m-t-sm"></i><span>mdi-action-note-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-open-in-browser i-24 m-t-sm"></i><span>mdi-action-open-in-browser</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-open-in-new i-24 m-t-sm"></i><span>mdi-action-open-in-new</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-open-with i-24 m-t-sm"></i><span>mdi-action-open-with</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-pageview i-24 m-t-sm"></i><span>mdi-action-pageview</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-payment i-24 m-t-sm"></i><span>mdi-action-payment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-camera-mic i-24 m-t-sm"></i><span>mdi-action-perm-camera-mic</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-contact-cal i-24 m-t-sm"></i><span>mdi-action-perm-contact-cal</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-data-setting i-24 m-t-sm"></i><span>mdi-action-perm-data-setting</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-device-info i-24 m-t-sm"></i><span>mdi-action-perm-device-info</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-identity i-24 m-t-sm"></i><span>mdi-action-perm-identity</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-media i-24 m-t-sm"></i><span>mdi-action-perm-media</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-phone-msg i-24 m-t-sm"></i><span>mdi-action-perm-phone-msg</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-perm-scan-wifi i-24 m-t-sm"></i><span>mdi-action-perm-scan-wifi</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-picture-in-picture i-24 m-t-sm"></i><span>mdi-action-picture-in-picture</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-polymer i-24 m-t-sm"></i><span>mdi-action-polymer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-print i-24 m-t-sm"></i><span>mdi-action-print</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-query-builder i-24 m-t-sm"></i><span>mdi-action-query-builder</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-question-answer i-24 m-t-sm"></i><span>mdi-action-question-answer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-receipt i-24 m-t-sm"></i><span>mdi-action-receipt</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-redeem i-24 m-t-sm"></i><span>mdi-action-redeem</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-report-problem i-24 m-t-sm"></i><span>mdi-action-report-problem</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-restore i-24 m-t-sm"></i><span>mdi-action-restore</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-room i-24 m-t-sm"></i><span>mdi-action-room</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-schedule i-24 m-t-sm"></i><span>mdi-action-schedule</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-search i-24 m-t-sm"></i><span>mdi-action-search</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings i-24 m-t-sm"></i><span>mdi-action-settings</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-applications i-24 m-t-sm"></i><span>mdi-action-settings-applications</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-backup-restore i-24 m-t-sm"></i><span>mdi-action-settings-backup-restore</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-bluetooth i-24 m-t-sm"></i><span>mdi-action-settings-bluetooth</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-cell i-24 m-t-sm"></i><span>mdi-action-settings-cell</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-display i-24 m-t-sm"></i><span>mdi-action-settings-display</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-ethernet i-24 m-t-sm"></i><span>mdi-action-settings-ethernet</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-input-antenna i-24 m-t-sm"></i><span>mdi-action-settings-input-antenna</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-input-component i-24 m-t-sm"></i><span>mdi-action-settings-input-component</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-input-composite i-24 m-t-sm"></i><span>mdi-action-settings-input-composite</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-input-hdmi i-24 m-t-sm"></i><span>mdi-action-settings-input-hdmi</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-input-svideo i-24 m-t-sm"></i><span>mdi-action-settings-input-svideo</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-overscan i-24 m-t-sm"></i><span>mdi-action-settings-overscan</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-phone i-24 m-t-sm"></i><span>mdi-action-settings-phone</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-power i-24 m-t-sm"></i><span>mdi-action-settings-power</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-remote i-24 m-t-sm"></i><span>mdi-action-settings-remote</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-settings-voice i-24 m-t-sm"></i><span>mdi-action-settings-voice</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-shop i-24 m-t-sm"></i><span>mdi-action-shop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-shop-two i-24 m-t-sm"></i><span>mdi-action-shop-two</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-shopping-basket i-24 m-t-sm"></i><span>mdi-action-shopping-basket</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-shopping-cart i-24 m-t-sm"></i><span>mdi-action-shopping-cart</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-speaker-notes i-24 m-t-sm"></i><span>mdi-action-speaker-notes</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-spellcheck i-24 m-t-sm"></i><span>mdi-action-spellcheck</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-star-rate i-24 m-t-sm"></i><span>mdi-action-star-rate</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-stars i-24 m-t-sm"></i><span>mdi-action-stars</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-store i-24 m-t-sm"></i><span>mdi-action-store</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-subject i-24 m-t-sm"></i><span>mdi-action-subject</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-swap-horiz i-24 m-t-sm"></i><span>mdi-action-swap-horiz</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-swap-vert i-24 m-t-sm"></i><span>mdi-action-swap-vert</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-swap-vert-circle i-24 m-t-sm"></i><span>mdi-action-swap-vert-circle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-system-update-tv i-24 m-t-sm"></i><span>mdi-action-system-update-tv</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-tab i-24 m-t-sm"></i><span>mdi-action-tab</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-tab-unselected i-24 m-t-sm"></i><span>mdi-action-tab-unselected</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-theaters i-24 m-t-sm"></i><span>mdi-action-theaters</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-thumb-down i-24 m-t-sm"></i><span>mdi-action-thumb-down</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-thumb-up i-24 m-t-sm"></i><span>mdi-action-thumb-up</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-thumbs-up-down i-24 m-t-sm"></i><span>mdi-action-thumbs-up-down</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-toc i-24 m-t-sm"></i><span>mdi-action-toc</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-today i-24 m-t-sm"></i><span>mdi-action-today</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-track-changes i-24 m-t-sm"></i><span>mdi-action-track-changes</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-translate i-24 m-t-sm"></i><span>mdi-action-translate</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-trending-down i-24 m-t-sm"></i><span>mdi-action-trending-down</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-trending-neutral i-24 m-t-sm"></i><span>mdi-action-trending-neutral</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-trending-up i-24 m-t-sm"></i><span>mdi-action-trending-up</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-turned-in i-24 m-t-sm"></i><span>mdi-action-turned-in</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-turned-in-not i-24 m-t-sm"></i><span>mdi-action-turned-in-not</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-verified-user i-24 m-t-sm"></i><span>mdi-action-verified-user</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-agenda i-24 m-t-sm"></i><span>mdi-action-view-agenda</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-array i-24 m-t-sm"></i><span>mdi-action-view-array</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-carousel i-24 m-t-sm"></i><span>mdi-action-view-carousel</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-column i-24 m-t-sm"></i><span>mdi-action-view-column</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-day i-24 m-t-sm"></i><span>mdi-action-view-day</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-headline i-24 m-t-sm"></i><span>mdi-action-view-headline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-list i-24 m-t-sm"></i><span>mdi-action-view-list</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-module i-24 m-t-sm"></i><span>mdi-action-view-module</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-quilt i-24 m-t-sm"></i><span>mdi-action-view-quilt</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-stream i-24 m-t-sm"></i><span>mdi-action-view-stream</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-view-week i-24 m-t-sm"></i><span>mdi-action-view-week</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-visibility i-24 m-t-sm"></i><span>mdi-action-visibility</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-visibility-off i-24 m-t-sm"></i><span>mdi-action-visibility-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-wallet-giftcard i-24 m-t-sm"></i><span>mdi-action-wallet-giftcard</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-wallet-membership i-24 m-t-sm"></i><span>mdi-action-wallet-membership</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-wallet-travel i-24 m-t-sm"></i><span>mdi-action-wallet-travel</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-action-work i-24 m-t-sm"></i><span>mdi-action-work</span></div>
      </div>

      <h4 class="page-header">AV</h4>
      <div id="av" class="row list-icon">
        <div class="col-xs-6 col-md-4"><i class="mdi-av-album i-24 m-t-sm"></i><span>mdi-av-album</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-timer i-24 m-t-sm"></i><span>mdi-av-timer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-closed-caption i-24 m-t-sm"></i><span>mdi-av-closed-caption</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-equalizer i-24 m-t-sm"></i><span>mdi-av-equalizer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-explicit i-24 m-t-sm"></i><span>mdi-av-explicit</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-fast-forward i-24 m-t-sm"></i><span>mdi-av-fast-forward</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-fast-rewind i-24 m-t-sm"></i><span>mdi-av-fast-rewind</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-games i-24 m-t-sm"></i><span>mdi-av-games</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-hearing i-24 m-t-sm"></i><span>mdi-av-hearing</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-high-quality i-24 m-t-sm"></i><span>mdi-av-high-quality</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-loop i-24 m-t-sm"></i><span>mdi-av-loop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-mic i-24 m-t-sm"></i><span>mdi-av-mic</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-mic-none i-24 m-t-sm"></i><span>mdi-av-mic-none</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-mic-off i-24 m-t-sm"></i><span>mdi-av-mic-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-movie i-24 m-t-sm"></i><span>mdi-av-movie</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-my-library-add i-24 m-t-sm"></i><span>mdi-av-my-library-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-my-library-books i-24 m-t-sm"></i><span>mdi-av-my-library-books</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-my-library-music i-24 m-t-sm"></i><span>mdi-av-my-library-music</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-new-releases i-24 m-t-sm"></i><span>mdi-av-new-releases</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-not-interested i-24 m-t-sm"></i><span>mdi-av-not-interested</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-pause i-24 m-t-sm"></i><span>mdi-av-pause</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-pause-circle-fill i-24 m-t-sm"></i><span>mdi-av-pause-circle-fill</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-pause-circle-outline i-24 m-t-sm"></i><span>mdi-av-pause-circle-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-play-arrow i-24 m-t-sm"></i><span>mdi-av-play-arrow</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-play-circle-fill i-24 m-t-sm"></i><span>mdi-av-play-circle-fill</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-play-circle-outline i-24 m-t-sm"></i><span>mdi-av-play-circle-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-play-shopping-bag i-24 m-t-sm"></i><span>mdi-av-play-shopping-bag</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-playlist-add i-24 m-t-sm"></i><span>mdi-av-playlist-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-queue i-24 m-t-sm"></i><span>mdi-av-queue</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-queue-music i-24 m-t-sm"></i><span>mdi-av-queue-music</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-radio i-24 m-t-sm"></i><span>mdi-av-radio</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-recent-actors i-24 m-t-sm"></i><span>mdi-av-recent-actors</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-repeat i-24 m-t-sm"></i><span>mdi-av-repeat</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-repeat-one i-24 m-t-sm"></i><span>mdi-av-repeat-one</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-replay i-24 m-t-sm"></i><span>mdi-av-replay</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-shuffle i-24 m-t-sm"></i><span>mdi-av-shuffle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-skip-next i-24 m-t-sm"></i><span>mdi-av-skip-next</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-skip-previous i-24 m-t-sm"></i><span>mdi-av-skip-previous</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-snooze i-24 m-t-sm"></i><span>mdi-av-snooze</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-stop i-24 m-t-sm"></i><span>mdi-av-stop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-subtitles i-24 m-t-sm"></i><span>mdi-av-subtitles</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-surround-sound i-24 m-t-sm"></i><span>mdi-av-surround-sound</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-video-collection i-24 m-t-sm"></i><span>mdi-av-video-collection</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-videocam i-24 m-t-sm"></i><span>mdi-av-videocam</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-videocam-off i-24 m-t-sm"></i><span>mdi-av-videocam-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-volume-down i-24 m-t-sm"></i><span>mdi-av-volume-down</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-volume-mute i-24 m-t-sm"></i><span>mdi-av-volume-mute</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-volume-off i-24 m-t-sm"></i><span>mdi-av-volume-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-volume-up i-24 m-t-sm"></i><span>mdi-av-volume-up</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-av-web i-24 m-t-sm"></i><span>mdi-av-web</span></div>
      </div>

      <h4 class="page-header">Communication</h4>
      <div id="communication" class="row list-icon">
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-business i-24 m-t-sm"></i><span>mdi-communication-business</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call i-24 m-t-sm"></i><span>mdi-communication-call</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call-end i-24 m-t-sm"></i><span>mdi-communication-call-end</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call-made i-24 m-t-sm"></i><span>mdi-communication-call-made</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call-merge i-24 m-t-sm"></i><span>mdi-communication-call-merge</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call-missed i-24 m-t-sm"></i><span>mdi-communication-call-missed</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call-received i-24 m-t-sm"></i><span>mdi-communication-call-received</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-call-split i-24 m-t-sm"></i><span>mdi-communication-call-split</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-chat i-24 m-t-sm"></i><span>mdi-communication-chat</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-clear-all i-24 m-t-sm"></i><span>mdi-communication-clear-all</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-comment i-24 m-t-sm"></i><span>mdi-communication-comment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-contacts i-24 m-t-sm"></i><span>mdi-communication-contacts</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-dialer-sip i-24 m-t-sm"></i><span>mdi-communication-dialer-sip</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-dialpad i-24 m-t-sm"></i><span>mdi-communication-dialpad</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-dnd-on i-24 m-t-sm"></i><span>mdi-communication-dnd-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-email i-24 m-t-sm"></i><span>mdi-communication-email</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-forum i-24 m-t-sm"></i><span>mdi-communication-forum</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-import-export i-24 m-t-sm"></i><span>mdi-communication-import-export</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-invert-colors-off i-24 m-t-sm"></i><span>mdi-communication-invert-colors-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-invert-colors-on i-24 m-t-sm"></i><span>mdi-communication-invert-colors-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-live-help i-24 m-t-sm"></i><span>mdi-communication-live-help</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-location-off i-24 m-t-sm"></i><span>mdi-communication-location-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-location-on i-24 m-t-sm"></i><span>mdi-communication-location-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-message i-24 m-t-sm"></i><span>mdi-communication-message</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-messenger i-24 m-t-sm"></i><span>mdi-communication-messenger</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-no-sim i-24 m-t-sm"></i><span>mdi-communication-no-sim</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-phone i-24 m-t-sm"></i><span>mdi-communication-phone</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-portable-wifi-off i-24 m-t-sm"></i><span>mdi-communication-portable-wifi-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-quick-contacts-dialer i-24 m-t-sm"></i><span>mdi-communication-quick-contacts-dialer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-quick-contacts-mail i-24 m-t-sm"></i><span>mdi-communication-quick-contacts-mail</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-ring-volume i-24 m-t-sm"></i><span>mdi-communication-ring-volume</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-stay-current-landscape i-24 m-t-sm"></i><span>mdi-communication-stay-current-landscape</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-stay-current-portrait i-24 m-t-sm"></i><span>mdi-communication-stay-current-portrait</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-stay-primary-landscape i-24 m-t-sm"></i><span>mdi-communication-stay-primary-landscape</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-stay-primary-portrait i-24 m-t-sm"></i><span>mdi-communication-stay-primary-portrait</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-swap-calls i-24 m-t-sm"></i><span>mdi-communication-swap-calls</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-textsms i-24 m-t-sm"></i><span>mdi-communication-textsms</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-voicemail i-24 m-t-sm"></i><span>mdi-communication-voicemail</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-communication-vpn-key i-24 m-t-sm"></i><span>mdi-communication-vpn-key</span></div>
      </div>

      <h4 class="page-header">Content</h4>
      <div id="content" class="row list-icon">
        <div class="col-xs-6 col-md-4"><i class="mdi-content-add i-24 m-t-sm"></i><span>mdi-content-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-add-box i-24 m-t-sm"></i><span>mdi-content-add-box</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-add-circle i-24 m-t-sm"></i><span>mdi-content-add-circle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-add-circle-outline i-24 m-t-sm"></i><span>mdi-content-add-circle-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-archive i-24 m-t-sm"></i><span>mdi-content-archive</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-backspace i-24 m-t-sm"></i><span>mdi-content-backspace</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-block i-24 m-t-sm"></i><span>mdi-content-block</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-clear i-24 m-t-sm"></i><span>mdi-content-clear</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-content-copy i-24 m-t-sm"></i><span>mdi-content-content-copy</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-content-cut i-24 m-t-sm"></i><span>mdi-content-content-cut</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-content-paste i-24 m-t-sm"></i><span>mdi-content-content-paste</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-create i-24 m-t-sm"></i><span>mdi-content-create</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-drafts i-24 m-t-sm"></i><span>mdi-content-drafts</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-filter-list i-24 m-t-sm"></i><span>mdi-content-filter-list</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-flag i-24 m-t-sm"></i><span>mdi-content-flag</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-forward i-24 m-t-sm"></i><span>mdi-content-forward</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-gesture i-24 m-t-sm"></i><span>mdi-content-gesture</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-inbox i-24 m-t-sm"></i><span>mdi-content-inbox</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-link i-24 m-t-sm"></i><span>mdi-content-link</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-mail i-24 m-t-sm"></i><span>mdi-content-mail</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-markunread i-24 m-t-sm"></i><span>mdi-content-markunread</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-redo i-24 m-t-sm"></i><span>mdi-content-redo</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-remove i-24 m-t-sm"></i><span>mdi-content-remove</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-remove-circle i-24 m-t-sm"></i><span>mdi-content-remove-circle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-remove-circle-outline i-24 m-t-sm"></i><span>mdi-content-remove-circle-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-reply i-24 m-t-sm"></i><span>mdi-content-reply</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-reply-all i-24 m-t-sm"></i><span>mdi-content-reply-all</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-report i-24 m-t-sm"></i><span>mdi-content-report</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-save i-24 m-t-sm"></i><span>mdi-content-save</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-select-all i-24 m-t-sm"></i><span>mdi-content-select-all</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-send i-24 m-t-sm"></i><span>mdi-content-send</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-sort i-24 m-t-sm"></i><span>mdi-content-sort</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-text-format i-24 m-t-sm"></i><span>mdi-content-text-format</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-content-undo i-24 m-t-sm"></i><span>mdi-content-undo</span></div>
      </div>

      <h4 class="page-header">Device</h4>
      <div id="device" class="row list-icon">
        <div class="col-xs-6 col-md-4"><i class="mdi-device-access-alarm i-24 m-t-sm"></i><span>mdi-device-access-alarm</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-access-alarms i-24 m-t-sm"></i><span>mdi-device-access-alarms</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-access-time i-24 m-t-sm"></i><span>mdi-device-access-time</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-add-alarm i-24 m-t-sm"></i><span>mdi-device-add-alarm</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-airplanemode-off i-24 m-t-sm"></i><span>mdi-device-airplanemode-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-airplanemode-on i-24 m-t-sm"></i><span>mdi-device-airplanemode-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-20 i-24 m-t-sm"></i><span>mdi-device-battery-20</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-30 i-24 m-t-sm"></i><span>mdi-device-battery-30</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-50 i-24 m-t-sm"></i><span>mdi-device-battery-50</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-60 i-24 m-t-sm"></i><span>mdi-device-battery-60</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-80 i-24 m-t-sm"></i><span>mdi-device-battery-80</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-90 i-24 m-t-sm"></i><span>mdi-device-battery-90</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-alert i-24 m-t-sm"></i><span>mdi-device-battery-alert</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-20 i-24 m-t-sm"></i><span>mdi-device-battery-charging-20</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-30 i-24 m-t-sm"></i><span>mdi-device-battery-charging-30</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-50 i-24 m-t-sm"></i><span>mdi-device-battery-charging-50</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-60 i-24 m-t-sm"></i><span>mdi-device-battery-charging-60</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-80 i-24 m-t-sm"></i><span>mdi-device-battery-charging-80</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-90 i-24 m-t-sm"></i><span>mdi-device-battery-charging-90</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-charging-full i-24 m-t-sm"></i><span>mdi-device-battery-charging-full</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-full i-24 m-t-sm"></i><span>mdi-device-battery-full</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-std i-24 m-t-sm"></i><span>mdi-device-battery-std</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-battery-unknown i-24 m-t-sm"></i><span>mdi-device-battery-unknown</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-bluetooth i-24 m-t-sm"></i><span>mdi-device-bluetooth</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-bluetooth-connected i-24 m-t-sm"></i><span>mdi-device-bluetooth-connected</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-bluetooth-disabled i-24 m-t-sm"></i><span>mdi-device-bluetooth-disabled</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-bluetooth-searching i-24 m-t-sm"></i><span>mdi-device-bluetooth-searching</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-brightness-auto i-24 m-t-sm"></i><span>mdi-device-brightness-auto</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-brightness-high i-24 m-t-sm"></i><span>mdi-device-brightness-high</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-brightness-low i-24 m-t-sm"></i><span>mdi-device-brightness-low</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-brightness-medium i-24 m-t-sm"></i><span>mdi-device-brightness-medium</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-data-usage i-24 m-t-sm"></i><span>mdi-device-data-usage</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-developer-mode i-24 m-t-sm"></i><span>mdi-device-developer-mode</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-devices i-24 m-t-sm"></i><span>mdi-device-devices</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-dvr i-24 m-t-sm"></i><span>mdi-device-dvr</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-gps-fixed i-24 m-t-sm"></i><span>mdi-device-gps-fixed</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-gps-not-fixed i-24 m-t-sm"></i><span>mdi-device-gps-not-fixed</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-gps-off i-24 m-t-sm"></i><span>mdi-device-gps-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-location-disabled i-24 m-t-sm"></i><span>mdi-device-location-disabled</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-location-searching i-24 m-t-sm"></i><span>mdi-device-location-searching</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-multitrack-audio i-24 m-t-sm"></i><span>mdi-device-multitrack-audio</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-network-cell i-24 m-t-sm"></i><span>mdi-device-network-cell</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-network-wifi i-24 m-t-sm"></i><span>mdi-device-network-wifi</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-nfc i-24 m-t-sm"></i><span>mdi-device-nfc</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-now-wallpaper i-24 m-t-sm"></i><span>mdi-device-now-wallpaper</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-now-widgets i-24 m-t-sm"></i><span>mdi-device-now-widgets</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-screen-lock-landscape i-24 m-t-sm"></i><span>mdi-device-screen-lock-landscape</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-screen-lock-portrait i-24 m-t-sm"></i><span>mdi-device-screen-lock-portrait</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-screen-lock-rotation i-24 m-t-sm"></i><span>mdi-device-screen-lock-rotation</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-screen-rotation i-24 m-t-sm"></i><span>mdi-device-screen-rotation</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-sd-storage i-24 m-t-sm"></i><span>mdi-device-sd-storage</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-settings-system-daydream i-24 m-t-sm"></i><span>mdi-device-settings-system-daydream</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-0-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-0-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-1-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-1-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-2-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-2-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-3-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-3-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-4-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-4-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-connected-no-internet-0-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-connected-no-internet-0-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-connected-no-internet-1-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-connected-no-internet-1-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-connected-no-internet-2-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-connected-no-internet-2-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-connected-no-internet-3-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-connected-no-internet-3-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-connected-no-internet-4-bar i-24 m-t-sm"></i><span>mdi-device-signal-cellular-connected-no-internet-4-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-no-sim i-24 m-t-sm"></i><span>mdi-device-signal-cellular-no-sim</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-null i-24 m-t-sm"></i><span>mdi-device-signal-cellular-null</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-cellular-off i-24 m-t-sm"></i><span>mdi-device-signal-cellular-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-wifi-0-bar i-24 m-t-sm"></i><span>mdi-device-signal-wifi-0-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-wifi-1-bar i-24 m-t-sm"></i><span>mdi-device-signal-wifi-1-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-wifi-2-bar i-24 m-t-sm"></i><span>mdi-device-signal-wifi-2-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-wifi-3-bar i-24 m-t-sm"></i><span>mdi-device-signal-wifi-3-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-wifi-4-bar i-24 m-t-sm"></i><span>mdi-device-signal-wifi-4-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-signal-wifi-off i-24 m-t-sm"></i><span>mdi-device-signal-wifi-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-storage i-24 m-t-sm"></i><span>mdi-device-storage</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-usb i-24 m-t-sm"></i><span>mdi-device-usb</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-wifi-lock i-24 m-t-sm"></i><span>mdi-device-wifi-lock</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-device-wifi-tethering i-24 m-t-sm"></i><span>mdi-device-wifi-tethering</span></div>
      </div>

      <h4 class="page-header">Editor</h4>
      <div id="editor" class="row list-icon">

        <div class="col-xs-6 col-md-4"><i class="mdi-editor-attach-file i-24 m-t-sm"></i><span>mdi-editor-attach-file</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-attach-money i-24 m-t-sm"></i><span>mdi-editor-attach-money</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-all i-24 m-t-sm"></i><span>mdi-editor-border-all</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-bottom i-24 m-t-sm"></i><span>mdi-editor-border-bottom</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-clear i-24 m-t-sm"></i><span>mdi-editor-border-clear</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-color i-24 m-t-sm"></i><span>mdi-editor-border-color</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-horizontal i-24 m-t-sm"></i><span>mdi-editor-border-horizontal</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-inner i-24 m-t-sm"></i><span>mdi-editor-border-inner</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-left i-24 m-t-sm"></i><span>mdi-editor-border-left</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-outer i-24 m-t-sm"></i><span>mdi-editor-border-outer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-right i-24 m-t-sm"></i><span>mdi-editor-border-right</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-style i-24 m-t-sm"></i><span>mdi-editor-border-style</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-top i-24 m-t-sm"></i><span>mdi-editor-border-top</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-border-vertical i-24 m-t-sm"></i><span>mdi-editor-border-vertical</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-align-center i-24 m-t-sm"></i><span>mdi-editor-format-align-center</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-align-justify i-24 m-t-sm"></i><span>mdi-editor-format-align-justify</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-align-left i-24 m-t-sm"></i><span>mdi-editor-format-align-left</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-align-right i-24 m-t-sm"></i><span>mdi-editor-format-align-right</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-bold i-24 m-t-sm"></i><span>mdi-editor-format-bold</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-clear i-24 m-t-sm"></i><span>mdi-editor-format-clear</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-color-fill i-24 m-t-sm"></i><span>mdi-editor-format-color-fill</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-color-reset i-24 m-t-sm"></i><span>mdi-editor-format-color-reset</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-color-text i-24 m-t-sm"></i><span>mdi-editor-format-color-text</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-indent-decrease i-24 m-t-sm"></i><span>mdi-editor-format-indent-decrease</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-indent-increase i-24 m-t-sm"></i><span>mdi-editor-format-indent-increase</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-italic i-24 m-t-sm"></i><span>mdi-editor-format-italic</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-line-spacing i-24 m-t-sm"></i><span>mdi-editor-format-line-spacing</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-list-bulleted i-24 m-t-sm"></i><span>mdi-editor-format-list-bulleted</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-list-numbered i-24 m-t-sm"></i><span>mdi-editor-format-list-numbered</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-paint i-24 m-t-sm"></i><span>mdi-editor-format-paint</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-quote i-24 m-t-sm"></i><span>mdi-editor-format-quote</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-size i-24 m-t-sm"></i><span>mdi-editor-format-size</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-strikethrough i-24 m-t-sm"></i><span>mdi-editor-format-strikethrough</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-textdirection-l-to-r i-24 m-t-sm"></i><span>mdi-editor-format-textdirection-l-to-r</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-textdirection-r-to-l i-24 m-t-sm"></i><span>mdi-editor-format-textdirection-r-to-l</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-format-underline i-24 m-t-sm"></i><span>mdi-editor-format-underline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-functions i-24 m-t-sm"></i><span>mdi-editor-functions</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-chart i-24 m-t-sm"></i><span>mdi-editor-insert-chart</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-comment i-24 m-t-sm"></i><span>mdi-editor-insert-comment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-drive-file i-24 m-t-sm"></i><span>mdi-editor-insert-drive-file</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-emoticon i-24 m-t-sm"></i><span>mdi-editor-insert-emoticon</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-invitation i-24 m-t-sm"></i><span>mdi-editor-insert-invitation</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-link i-24 m-t-sm"></i><span>mdi-editor-insert-link</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-insert-photo i-24 m-t-sm"></i><span>mdi-editor-insert-photo</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-merge-type i-24 m-t-sm"></i><span>mdi-editor-merge-type</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-mode-comment i-24 m-t-sm"></i><span>mdi-editor-mode-comment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-mode-edit i-24 m-t-sm"></i><span>mdi-editor-mode-edit</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-publish i-24 m-t-sm"></i><span>mdi-editor-publish</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-vertical-align-bottom i-24 m-t-sm"></i><span>mdi-editor-vertical-align-bottom</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-vertical-align-center i-24 m-t-sm"></i><span>mdi-editor-vertical-align-center</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-vertical-align-top i-24 m-t-sm"></i><span>mdi-editor-vertical-align-top</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-editor-wrap-text i-24 m-t-sm"></i><span>mdi-editor-wrap-text</span></div>
      </div>

      <h4 class="page-header">File</h4>
      <div id="file" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-file-attachment i-24 m-t-sm"></i><span>mdi-file-attachment</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud i-24 m-t-sm"></i><span>mdi-file-cloud</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud-circle i-24 m-t-sm"></i><span>mdi-file-cloud-circle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud-done i-24 m-t-sm"></i><span>mdi-file-cloud-done</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud-download i-24 m-t-sm"></i><span>mdi-file-cloud-download</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud-off i-24 m-t-sm"></i><span>mdi-file-cloud-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud-queue i-24 m-t-sm"></i><span>mdi-file-cloud-queue</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-cloud-upload i-24 m-t-sm"></i><span>mdi-file-cloud-upload</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-file-download i-24 m-t-sm"></i><span>mdi-file-file-download</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-file-upload i-24 m-t-sm"></i><span>mdi-file-file-upload</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-folder i-24 m-t-sm"></i><span>mdi-file-folder</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-folder-open i-24 m-t-sm"></i><span>mdi-file-folder-open</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-file-folder-shared i-24 m-t-sm"></i><span>mdi-file-folder-shared</span></div>
      </div>

      <h4 class="page-header">Hardware</h4>
      <div id="hardware" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-cast i-24 m-t-sm"></i><span>mdi-hardware-cast</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-cast-connected i-24 m-t-sm"></i><span>mdi-hardware-cast-connected</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-computer i-24 m-t-sm"></i><span>mdi-hardware-computer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-desktop-mac i-24 m-t-sm"></i><span>mdi-hardware-desktop-mac</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-desktop-windows i-24 m-t-sm"></i><span>mdi-hardware-desktop-windows</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-dock i-24 m-t-sm"></i><span>mdi-hardware-dock</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-gamepad i-24 m-t-sm"></i><span>mdi-hardware-gamepad</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-headset i-24 m-t-sm"></i><span>mdi-hardware-headset</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-headset-mic i-24 m-t-sm"></i><span>mdi-hardware-headset-mic</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard i-24 m-t-sm"></i><span>mdi-hardware-keyboard</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-alt i-24 m-t-sm"></i><span>mdi-hardware-keyboard-alt</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-arrow-down i-24 m-t-sm"></i><span>mdi-hardware-keyboard-arrow-down</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-arrow-left i-24 m-t-sm"></i><span>mdi-hardware-keyboard-arrow-left</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-arrow-right i-24 m-t-sm"></i><span>mdi-hardware-keyboard-arrow-right</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-arrow-up i-24 m-t-sm"></i><span>mdi-hardware-keyboard-arrow-up</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-backspace i-24 m-t-sm"></i><span>mdi-hardware-keyboard-backspace</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-capslock i-24 m-t-sm"></i><span>mdi-hardware-keyboard-capslock</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-control i-24 m-t-sm"></i><span>mdi-hardware-keyboard-control</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-hide i-24 m-t-sm"></i><span>mdi-hardware-keyboard-hide</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-return i-24 m-t-sm"></i><span>mdi-hardware-keyboard-return</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-tab i-24 m-t-sm"></i><span>mdi-hardware-keyboard-tab</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-keyboard-voice i-24 m-t-sm"></i><span>mdi-hardware-keyboard-voice</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-laptop i-24 m-t-sm"></i><span>mdi-hardware-laptop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-laptop-chromebook i-24 m-t-sm"></i><span>mdi-hardware-laptop-chromebook</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-laptop-mac i-24 m-t-sm"></i><span>mdi-hardware-laptop-mac</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-laptop-windows i-24 m-t-sm"></i><span>mdi-hardware-laptop-windows</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-memory i-24 m-t-sm"></i><span>mdi-hardware-memory</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-mouse i-24 m-t-sm"></i><span>mdi-hardware-mouse</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-phone-android i-24 m-t-sm"></i><span>mdi-hardware-phone-android</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-phone-iphone i-24 m-t-sm"></i><span>mdi-hardware-phone-iphone</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-phonelink i-24 m-t-sm"></i><span>mdi-hardware-phonelink</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-phonelink-off i-24 m-t-sm"></i><span>mdi-hardware-phonelink-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-security i-24 m-t-sm"></i><span>mdi-hardware-security</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-sim-card i-24 m-t-sm"></i><span>mdi-hardware-sim-card</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-smartphone i-24 m-t-sm"></i><span>mdi-hardware-smartphone</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-speaker i-24 m-t-sm"></i><span>mdi-hardware-speaker</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-tablet i-24 m-t-sm"></i><span>mdi-hardware-tablet</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-tablet-android i-24 m-t-sm"></i><span>mdi-hardware-tablet-android</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-tablet-mac i-24 m-t-sm"></i><span>mdi-hardware-tablet-mac</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-tv i-24 m-t-sm"></i><span>mdi-hardware-tv</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-hardware-watch i-24 m-t-sm"></i><span>mdi-hardware-watch</span></div>
      </div>

      <h4 class="page-header">Image</h4>
      <div id="image" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-image-add-to-photos i-24 m-t-sm"></i><span>mdi-image-add-to-photos</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-adjust i-24 m-t-sm"></i><span>mdi-image-adjust</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-assistant-photo i-24 m-t-sm"></i><span>mdi-image-assistant-photo</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-audiotrack i-24 m-t-sm"></i><span>mdi-image-audiotrack</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-blur-circular i-24 m-t-sm"></i><span>mdi-image-blur-circular</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-blur-linear i-24 m-t-sm"></i><span>mdi-image-blur-linear</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-blur-off i-24 m-t-sm"></i><span>mdi-image-blur-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-blur-on i-24 m-t-sm"></i><span>mdi-image-blur-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-1 i-24 m-t-sm"></i><span>mdi-image-brightness-1</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-2 i-24 m-t-sm"></i><span>mdi-image-brightness-2</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-3 i-24 m-t-sm"></i><span>mdi-image-brightness-3</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-4 i-24 m-t-sm"></i><span>mdi-image-brightness-4</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-5 i-24 m-t-sm"></i><span>mdi-image-brightness-5</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-6 i-24 m-t-sm"></i><span>mdi-image-brightness-6</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brightness-7 i-24 m-t-sm"></i><span>mdi-image-brightness-7</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-brush i-24 m-t-sm"></i><span>mdi-image-brush</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-camera i-24 m-t-sm"></i><span>mdi-image-camera</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-camera-alt i-24 m-t-sm"></i><span>mdi-image-camera-alt</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-camera-front i-24 m-t-sm"></i><span>mdi-image-camera-front</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-camera-rear i-24 m-t-sm"></i><span>mdi-image-camera-rear</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-camera-roll i-24 m-t-sm"></i><span>mdi-image-camera-roll</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-center-focus-strong i-24 m-t-sm"></i><span>mdi-image-center-focus-strong</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-center-focus-weak i-24 m-t-sm"></i><span>mdi-image-center-focus-weak</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-collections i-24 m-t-sm"></i><span>mdi-image-collections</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-color-lens i-24 m-t-sm"></i><span>mdi-image-color-lens</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-colorize i-24 m-t-sm"></i><span>mdi-image-colorize</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-compare i-24 m-t-sm"></i><span>mdi-image-compare</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-control-point i-24 m-t-sm"></i><span>mdi-image-control-point</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-control-point-duplicate i-24 m-t-sm"></i><span>mdi-image-control-point-duplicate</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-16-9 i-24 m-t-sm"></i><span>mdi-image-crop-16-9</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop i-24 m-t-sm"></i><span>mdi-image-crop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-3-2 i-24 m-t-sm"></i><span>mdi-image-crop-3-2</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-5-4 i-24 m-t-sm"></i><span>mdi-image-crop-5-4</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-7-5 i-24 m-t-sm"></i><span>mdi-image-crop-7-5</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-din i-24 m-t-sm"></i><span>mdi-image-crop-din</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-free i-24 m-t-sm"></i><span>mdi-image-crop-free</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-landscape i-24 m-t-sm"></i><span>mdi-image-crop-landscape</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-original i-24 m-t-sm"></i><span>mdi-image-crop-original</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-portrait i-24 m-t-sm"></i><span>mdi-image-crop-portrait</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-crop-square i-24 m-t-sm"></i><span>mdi-image-crop-square</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-dehaze i-24 m-t-sm"></i><span>mdi-image-dehaze</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-details i-24 m-t-sm"></i><span>mdi-image-details</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-edit i-24 m-t-sm"></i><span>mdi-image-edit</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-exposure i-24 m-t-sm"></i><span>mdi-image-exposure</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-exposure-minus-1 i-24 m-t-sm"></i><span>mdi-image-exposure-minus-1</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-exposure-minus-2 i-24 m-t-sm"></i><span>mdi-image-exposure-minus-2</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-exposure-plus-1 i-24 m-t-sm"></i><span>mdi-image-exposure-plus-1</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-exposure-plus-2 i-24 m-t-sm"></i><span>mdi-image-exposure-plus-2</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-exposure-zero i-24 m-t-sm"></i><span>mdi-image-exposure-zero</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-1 i-24 m-t-sm"></i><span>mdi-image-filter-1</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter i-24 m-t-sm"></i><span>mdi-image-filter</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-2 i-24 m-t-sm"></i><span>mdi-image-filter-2</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-3 i-24 m-t-sm"></i><span>mdi-image-filter-3</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-4 i-24 m-t-sm"></i><span>mdi-image-filter-4</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-5 i-24 m-t-sm"></i><span>mdi-image-filter-5</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-6 i-24 m-t-sm"></i><span>mdi-image-filter-6</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-7 i-24 m-t-sm"></i><span>mdi-image-filter-7</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-8 i-24 m-t-sm"></i><span>mdi-image-filter-8</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-9 i-24 m-t-sm"></i><span>mdi-image-filter-9</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-9-plus i-24 m-t-sm"></i><span>mdi-image-filter-9-plus</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-b-and-w i-24 m-t-sm"></i><span>mdi-image-filter-b-and-w</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-center-focus i-24 m-t-sm"></i><span>mdi-image-filter-center-focus</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-drama i-24 m-t-sm"></i><span>mdi-image-filter-drama</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-frames i-24 m-t-sm"></i><span>mdi-image-filter-frames</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-hdr i-24 m-t-sm"></i><span>mdi-image-filter-hdr</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-none i-24 m-t-sm"></i><span>mdi-image-filter-none</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-tilt-shift i-24 m-t-sm"></i><span>mdi-image-filter-tilt-shift</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-filter-vintage i-24 m-t-sm"></i><span>mdi-image-filter-vintage</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-flare i-24 m-t-sm"></i><span>mdi-image-flare</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-flash-auto i-24 m-t-sm"></i><span>mdi-image-flash-auto</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-flash-off i-24 m-t-sm"></i><span>mdi-image-flash-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-flash-on i-24 m-t-sm"></i><span>mdi-image-flash-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-flip i-24 m-t-sm"></i><span>mdi-image-flip</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-gradient i-24 m-t-sm"></i><span>mdi-image-gradient</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-grain i-24 m-t-sm"></i><span>mdi-image-grain</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-grid-off i-24 m-t-sm"></i><span>mdi-image-grid-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-grid-on i-24 m-t-sm"></i><span>mdi-image-grid-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-hdr-off i-24 m-t-sm"></i><span>mdi-image-hdr-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-hdr-on i-24 m-t-sm"></i><span>mdi-image-hdr-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-hdr-strong i-24 m-t-sm"></i><span>mdi-image-hdr-strong</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-hdr-weak i-24 m-t-sm"></i><span>mdi-image-hdr-weak</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-healing i-24 m-t-sm"></i><span>mdi-image-healing</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-image i-24 m-t-sm"></i><span>mdi-image-image</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-image-aspect-ratio i-24 m-t-sm"></i><span>mdi-image-image-aspect-ratio</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-iso i-24 m-t-sm"></i><span>mdi-image-iso</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-landscape i-24 m-t-sm"></i><span>mdi-image-landscape</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-leak-add i-24 m-t-sm"></i><span>mdi-image-leak-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-leak-remove i-24 m-t-sm"></i><span>mdi-image-leak-remove</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-lens i-24 m-t-sm"></i><span>mdi-image-lens</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks i-24 m-t-sm"></i><span>mdi-image-looks</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks-3 i-24 m-t-sm"></i><span>mdi-image-looks-3</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks-4 i-24 m-t-sm"></i><span>mdi-image-looks-4</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks-5 i-24 m-t-sm"></i><span>mdi-image-looks-5</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks-6 i-24 m-t-sm"></i><span>mdi-image-looks-6</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks-one i-24 m-t-sm"></i><span>mdi-image-looks-one</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-looks-two i-24 m-t-sm"></i><span>mdi-image-looks-two</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-loupe i-24 m-t-sm"></i><span>mdi-image-loupe</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-movie-creation i-24 m-t-sm"></i><span>mdi-image-movie-creation</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-nature i-24 m-t-sm"></i><span>mdi-image-nature</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-nature-people i-24 m-t-sm"></i><span>mdi-image-nature-people</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-navigate-before i-24 m-t-sm"></i><span>mdi-image-navigate-before</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-navigate-next i-24 m-t-sm"></i><span>mdi-image-navigate-next</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-palette i-24 m-t-sm"></i><span>mdi-image-palette</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-panorama i-24 m-t-sm"></i><span>mdi-image-panorama</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-panorama-fisheye i-24 m-t-sm"></i><span>mdi-image-panorama-fisheye</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-panorama-horizontal i-24 m-t-sm"></i><span>mdi-image-panorama-horizontal</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-panorama-vertical i-24 m-t-sm"></i><span>mdi-image-panorama-vertical</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-panorama-wide-angle i-24 m-t-sm"></i><span>mdi-image-panorama-wide-angle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-photo i-24 m-t-sm"></i><span>mdi-image-photo</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-photo-album i-24 m-t-sm"></i><span>mdi-image-photo-album</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-photo-camera i-24 m-t-sm"></i><span>mdi-image-photo-camera</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-photo-library i-24 m-t-sm"></i><span>mdi-image-photo-library</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-portrait i-24 m-t-sm"></i><span>mdi-image-portrait</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-remove-red-eye i-24 m-t-sm"></i><span>mdi-image-remove-red-eye</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-rotate-left i-24 m-t-sm"></i><span>mdi-image-rotate-left</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-rotate-right i-24 m-t-sm"></i><span>mdi-image-rotate-right</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-slideshow i-24 m-t-sm"></i><span>mdi-image-slideshow</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-straighten i-24 m-t-sm"></i><span>mdi-image-straighten</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-style i-24 m-t-sm"></i><span>mdi-image-style</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-switch-camera i-24 m-t-sm"></i><span>mdi-image-switch-camera</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-switch-video i-24 m-t-sm"></i><span>mdi-image-switch-video</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-tag-faces i-24 m-t-sm"></i><span>mdi-image-tag-faces</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-texture i-24 m-t-sm"></i><span>mdi-image-texture</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-timelapse i-24 m-t-sm"></i><span>mdi-image-timelapse</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-timer-10 i-24 m-t-sm"></i><span>mdi-image-timer-10</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-timer i-24 m-t-sm"></i><span>mdi-image-timer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-timer-3 i-24 m-t-sm"></i><span>mdi-image-timer-3</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-timer-auto i-24 m-t-sm"></i><span>mdi-image-timer-auto</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-timer-off i-24 m-t-sm"></i><span>mdi-image-timer-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-tonality i-24 m-t-sm"></i><span>mdi-image-tonality</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-transform i-24 m-t-sm"></i><span>mdi-image-transform</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-tune i-24 m-t-sm"></i><span>mdi-image-tune</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-wb-auto i-24 m-t-sm"></i><span>mdi-image-wb-auto</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-wb-cloudy i-24 m-t-sm"></i><span>mdi-image-wb-cloudy</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-wb-incandescent i-24 m-t-sm"></i><span>mdi-image-wb-incandescent</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-wb-irradescent i-24 m-t-sm"></i><span>mdi-image-wb-irradescent</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-image-wb-sunny i-24 m-t-sm"></i><span>mdi-image-wb-sunny</span></div>
      </div>

      <h4 class="page-header">Maps</h4>
      <div id="maps" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-maps-beenhere i-24 m-t-sm"></i><span>mdi-maps-beenhere</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions i-24 m-t-sm"></i><span>mdi-maps-directions</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-bike i-24 m-t-sm"></i><span>mdi-maps-directions-bike</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-bus i-24 m-t-sm"></i><span>mdi-maps-directions-bus</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-car i-24 m-t-sm"></i><span>mdi-maps-directions-car</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-ferry i-24 m-t-sm"></i><span>mdi-maps-directions-ferry</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-subway i-24 m-t-sm"></i><span>mdi-maps-directions-subway</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-train i-24 m-t-sm"></i><span>mdi-maps-directions-train</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-transit i-24 m-t-sm"></i><span>mdi-maps-directions-transit</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-directions-walk i-24 m-t-sm"></i><span>mdi-maps-directions-walk</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-flight i-24 m-t-sm"></i><span>mdi-maps-flight</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-hotel i-24 m-t-sm"></i><span>mdi-maps-hotel</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-layers i-24 m-t-sm"></i><span>mdi-maps-layers</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-layers-clear i-24 m-t-sm"></i><span>mdi-maps-layers-clear</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-airport i-24 m-t-sm"></i><span>mdi-maps-local-airport</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-atm i-24 m-t-sm"></i><span>mdi-maps-local-atm</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-attraction i-24 m-t-sm"></i><span>mdi-maps-local-attraction</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-bar i-24 m-t-sm"></i><span>mdi-maps-local-bar</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-cafe i-24 m-t-sm"></i><span>mdi-maps-local-cafe</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-car-wash i-24 m-t-sm"></i><span>mdi-maps-local-car-wash</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-convenience-store i-24 m-t-sm"></i><span>mdi-maps-local-convenience-store</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-drink i-24 m-t-sm"></i><span>mdi-maps-local-drink</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-florist i-24 m-t-sm"></i><span>mdi-maps-local-florist</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-gas-station i-24 m-t-sm"></i><span>mdi-maps-local-gas-station</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-grocery-store i-24 m-t-sm"></i><span>mdi-maps-local-grocery-store</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-hospital i-24 m-t-sm"></i><span>mdi-maps-local-hospital</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-hotel i-24 m-t-sm"></i><span>mdi-maps-local-hotel</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-laundry-service i-24 m-t-sm"></i><span>mdi-maps-local-laundry-service</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-library i-24 m-t-sm"></i><span>mdi-maps-local-library</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-mall i-24 m-t-sm"></i><span>mdi-maps-local-mall</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-movies i-24 m-t-sm"></i><span>mdi-maps-local-movies</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-offer i-24 m-t-sm"></i><span>mdi-maps-local-offer</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-parking i-24 m-t-sm"></i><span>mdi-maps-local-parking</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-pharmacy i-24 m-t-sm"></i><span>mdi-maps-local-pharmacy</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-phone i-24 m-t-sm"></i><span>mdi-maps-local-phone</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-pizza i-24 m-t-sm"></i><span>mdi-maps-local-pizza</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-play i-24 m-t-sm"></i><span>mdi-maps-local-play</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-post-office i-24 m-t-sm"></i><span>mdi-maps-local-post-office</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-print-shop i-24 m-t-sm"></i><span>mdi-maps-local-print-shop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-restaurant i-24 m-t-sm"></i><span>mdi-maps-local-restaurant</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-see i-24 m-t-sm"></i><span>mdi-maps-local-see</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-shipping i-24 m-t-sm"></i><span>mdi-maps-local-shipping</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-local-taxi i-24 m-t-sm"></i><span>mdi-maps-local-taxi</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-location-history i-24 m-t-sm"></i><span>mdi-maps-location-history</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-map i-24 m-t-sm"></i><span>mdi-maps-map</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-my-location i-24 m-t-sm"></i><span>mdi-maps-my-location</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-navigation i-24 m-t-sm"></i><span>mdi-maps-navigation</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-pin-drop i-24 m-t-sm"></i><span>mdi-maps-pin-drop</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-place i-24 m-t-sm"></i><span>mdi-maps-place</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-rate-review i-24 m-t-sm"></i><span>mdi-maps-rate-review</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-restaurant-menu i-24 m-t-sm"></i><span>mdi-maps-restaurant-menu</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-satellite i-24 m-t-sm"></i><span>mdi-maps-satellite</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-store-mall-directory i-24 m-t-sm"></i><span>mdi-maps-store-mall-directory</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-terrain i-24 m-t-sm"></i><span>mdi-maps-terrain</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-maps-traffic i-24 m-t-sm"></i><span>mdi-maps-traffic</span></div>
      </div>

      <h4 class="page-header">Navigation</h4>
      <div id="navigation" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-apps i-24 m-t-sm"></i><span>mdi-navigation-apps</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-arrow-back i-24 m-t-sm"></i><span>mdi-navigation-arrow-back</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-arrow-drop-down i-24 m-t-sm"></i><span>mdi-navigation-arrow-drop-down</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-arrow-drop-down-circle i-24 m-t-sm"></i><span>mdi-navigation-arrow-drop-down-circle</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-arrow-drop-up i-24 m-t-sm"></i><span>mdi-navigation-arrow-drop-up</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-arrow-forward i-24 m-t-sm"></i><span>mdi-navigation-arrow-forward</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-cancel i-24 m-t-sm"></i><span>mdi-navigation-cancel</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-check i-24 m-t-sm"></i><span>mdi-navigation-check</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-chevron-left i-24 m-t-sm"></i><span>mdi-navigation-chevron-left</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-chevron-right i-24 m-t-sm"></i><span>mdi-navigation-chevron-right</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-close i-24 m-t-sm"></i><span>mdi-navigation-close</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-expand-less i-24 m-t-sm"></i><span>mdi-navigation-expand-less</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-expand-more i-24 m-t-sm"></i><span>mdi-navigation-expand-more</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-fullscreen i-24 m-t-sm"></i><span>mdi-navigation-fullscreen</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-fullscreen-exit i-24 m-t-sm"></i><span>mdi-navigation-fullscreen-exit</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-menu i-24 m-t-sm"></i><span>mdi-navigation-menu</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-more-horiz i-24 m-t-sm"></i><span>mdi-navigation-more-horiz</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-more-vert i-24 m-t-sm"></i><span>mdi-navigation-more-vert</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-refresh i-24 m-t-sm"></i><span>mdi-navigation-refresh</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-unfold-less i-24 m-t-sm"></i><span>mdi-navigation-unfold-less</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-navigation-unfold-more i-24 m-t-sm"></i><span>mdi-navigation-unfold-more</span></div>
      </div>

      <h4 class="page-header">Notifications</h4>
      <div id="notifications" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-notification-adb i-24 m-t-sm"></i><span>mdi-notification-adb</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-bluetooth-audio i-24 m-t-sm"></i><span>mdi-notification-bluetooth-audio</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-disc-full i-24 m-t-sm"></i><span>mdi-notification-disc-full</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-dnd-forwardslash i-24 m-t-sm"></i><span>mdi-notification-dnd-forwardslash</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-do-not-disturb i-24 m-t-sm"></i><span>mdi-notification-do-not-disturb</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-drive-eta i-24 m-t-sm"></i><span>mdi-notification-drive-eta</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-event-available i-24 m-t-sm"></i><span>mdi-notification-event-available</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-event-busy i-24 m-t-sm"></i><span>mdi-notification-event-busy</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-event-note i-24 m-t-sm"></i><span>mdi-notification-event-note</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-folder-special i-24 m-t-sm"></i><span>mdi-notification-folder-special</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-mms i-24 m-t-sm"></i><span>mdi-notification-mms</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-more i-24 m-t-sm"></i><span>mdi-notification-more</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-network-locked i-24 m-t-sm"></i><span>mdi-notification-network-locked</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-phone-bluetooth-speaker i-24 m-t-sm"></i><span>mdi-notification-phone-bluetooth-speaker</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-phone-forwarded i-24 m-t-sm"></i><span>mdi-notification-phone-forwarded</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-phone-in-talk i-24 m-t-sm"></i><span>mdi-notification-phone-in-talk</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-phone-locked i-24 m-t-sm"></i><span>mdi-notification-phone-locked</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-phone-missed i-24 m-t-sm"></i><span>mdi-notification-phone-missed</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-phone-paused i-24 m-t-sm"></i><span>mdi-notification-phone-paused</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-play-download i-24 m-t-sm"></i><span>mdi-notification-play-download</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-play-install i-24 m-t-sm"></i><span>mdi-notification-play-install</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sd-card i-24 m-t-sm"></i><span>mdi-notification-sd-card</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sim-card-alert i-24 m-t-sm"></i><span>mdi-notification-sim-card-alert</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sms i-24 m-t-sm"></i><span>mdi-notification-sms</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sms-failed i-24 m-t-sm"></i><span>mdi-notification-sms-failed</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sync i-24 m-t-sm"></i><span>mdi-notification-sync</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sync-disabled i-24 m-t-sm"></i><span>mdi-notification-sync-disabled</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-sync-problem i-24 m-t-sm"></i><span>mdi-notification-sync-problem</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-system-update i-24 m-t-sm"></i><span>mdi-notification-system-update</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-tap-and-play i-24 m-t-sm"></i><span>mdi-notification-tap-and-play</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-time-to-leave i-24 m-t-sm"></i><span>mdi-notification-time-to-leave</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-vibration i-24 m-t-sm"></i><span>mdi-notification-vibration</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-voice-chat i-24 m-t-sm"></i><span>mdi-notification-voice-chat</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-notification-vpn-lock i-24 m-t-sm"></i><span>mdi-notification-vpn-lock</span></div>
      </div>

      <h4 class="page-header">Social</h4>
      <div id="social" class="row list-icon">
        

        <div class="col-xs-6 col-md-4"><i class="mdi-social-cake i-24 m-t-sm"></i><span>mdi-social-cake</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-domain i-24 m-t-sm"></i><span>mdi-social-domain</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-group i-24 m-t-sm"></i><span>mdi-social-group</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-group-add i-24 m-t-sm"></i><span>mdi-social-group-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-location-city i-24 m-t-sm"></i><span>mdi-social-location-city</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-mood i-24 m-t-sm"></i><span>mdi-social-mood</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-notifications i-24 m-t-sm"></i><span>mdi-social-notifications</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-notifications-none i-24 m-t-sm"></i><span>mdi-social-notifications-none</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-notifications-off i-24 m-t-sm"></i><span>mdi-social-notifications-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-notifications-on i-24 m-t-sm"></i><span>mdi-social-notifications-on</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-notifications-paused i-24 m-t-sm"></i><span>mdi-social-notifications-paused</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-pages i-24 m-t-sm"></i><span>mdi-social-pages</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-party-mode i-24 m-t-sm"></i><span>mdi-social-party-mode</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-people i-24 m-t-sm"></i><span>mdi-social-people</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-people-outline i-24 m-t-sm"></i><span>mdi-social-people-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-person i-24 m-t-sm"></i><span>mdi-social-person</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-person-add i-24 m-t-sm"></i><span>mdi-social-person-add</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-person-outline i-24 m-t-sm"></i><span>mdi-social-person-outline</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-plus-one i-24 m-t-sm"></i><span>mdi-social-plus-one</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-poll i-24 m-t-sm"></i><span>mdi-social-poll</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-public i-24 m-t-sm"></i><span>mdi-social-public</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-school i-24 m-t-sm"></i><span>mdi-social-school</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-share i-24 m-t-sm"></i><span>mdi-social-share</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-social-whatshot i-24 m-t-sm"></i><span>mdi-social-whatshot</span></div>
      </div>

      <h4 class="page-header">Toggle</h4>
      <div id="toggle" class="row list-icon">
        
        <div class="col-xs-6 col-md-4"><i class="mdi-toggle-check-box i-24 m-t-sm"></i><span>mdi-toggle-check-box</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-toggle-check-box-outline-blank i-24 m-t-sm"></i><span>mdi-toggle-check-box-outline-blank</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-toggle-radio-button-off i-24 m-t-sm"></i><span>mdi-toggle-radio-button-off</span></div>
        <div class="col-xs-6 col-md-4"><i class="mdi-toggle-radio-button-on i-24 m-t-sm"></i><span>mdi-toggle-radio-button-on</span>
        </div>
      </div>

    </div>
</div>
